name: ROLAND VAS
favicon: null
layout_spectrum: 0.12091361614875495
typography_spectrum: 0.03898598626255989
title: "It's just a blog about everything that interests me"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#8b0000'
    - '#f8ca8d'
    - '#2b2216'
    - '#6e5b3d'
  brandStrength: 0.875
  lightness: 0.125
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
